months_to_review: 3
search_phrase: google
category: technology
AP:
  url: https://apnews.com
  logo: //*[@class="Page-header-bar-logo"]
  search_button: //*[@class="SearchOverlay-search-button"]
  search_bar: //*[@class="SearchOverlay-search-input"]
  search_results_container: //*[@class="SearchResultsModule-results"]
  search_results: //*[@class="PagePromo"]
  next_page_button: //*[@class="Pagination-nextPage"]
new:
  image: Image
  title: PagePromo-title
  description: PagePromo-description
  date_container: PagePromo-date
  timestamp: data-timestamp
  money_amount_regex: (?:\$|£|\€|(?:USD|dollars))(\d+(?:,\d{3})*(?:\.\d{1,2})?)
first_child: :first-child
paths:
  output: ./output
delays:
  short: 5
  medium: 15
  long: 20
max_retries: 3